"""empty message

Revision ID: 92454ec55875
Revises: 78fed4aa6d9f
Create Date: 2023-12-15 03:55:37.094046

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92454ec55875'
down_revision = '78fed4aa6d9f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('itineraries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('itineraries', schema=None) as batch_op:
        batch_op.drop_column('total')

    # ### end Alembic commands ###
