"""empty message

Revision ID: b71df8aace9f
Revises: fb7d14dcafd2
Create Date: 2023-11-30 06:11:25.598974

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b71df8aace9f'
down_revision = 'fb7d14dcafd2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trip_details', schema=None) as batch_op:
        batch_op.alter_column('settled',
               existing_type=sa.FLOAT(),
               type_=sa.Boolean(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trip_details', schema=None) as batch_op:
        batch_op.alter_column('settled',
               existing_type=sa.Boolean(),
               type_=sa.FLOAT(),
               existing_nullable=True)

    # ### end Alembic commands ###
